Actions dropdown menu
RHEcosystemAppEng/cluster-iq-console pull request #35
Opened 2024-12-16 14:38 UTC by rhartuv

those changes are including the necessary changes to the clusters

2024-12-17 12:57 UTC, ikrispin commented on src/app/ClusterDetails/ClusterDetails.tsx
> +// }
Maybe we can delete these lines?

2024-12-18 17:14 UTC, r2dedios commented
Does this code enable or disable the Actions dropdown menu options based on the Cluster Status?
In other words, if the cluster is Stopped, Is the "Power Off" option available?

2024-12-19 09:24 UTC, vbelouso commented
@rhartuv @ikrispin 

1. Please install https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode to VSCode. It will format your code to a more consistent style.
2. You don't need an additional `DividerUsingDiv` component, use vanilla `<Divider />`. Place it one line above the code
```typescript
<PageSection type="tabs" variant={PageSectionVariants.light} isWidthLimited>
```
3. This code part is also not needed  because you don't use it in the code
```typescript
const [cluster, setClusterData] = useState<ClusterData>({
    count: 0,
    clusters: []
  });
```

2024-12-19 09:48 UTC, vbelouso requested changes
@rhartuv @ikrispin 

1. Please install https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode to VSCode. It will format your code to a more consistent style.
2. You don't need an additional `DividerUsingDiv` component, use vanilla <Divider />. Place it one line above the code `<PageSection type="tabs" variant={PageSectionVariants.light} isWidthLimited>`
3. This code part is also not needed because you don't use it in the code
```typescript
const [cluster, setClusterData] = useState<ClusterData>({
    count: 0,
    clusters: []
  });
```

2024-12-23 10:52 UTC, vbelouso commented
Good job, thanks @rhartuv @ikrispin

2024-12-23 10:52 UTC, merged

2024-12-23 10:58 UTC, r2dedios commented
Closes #21